name: Publish to FlakeHub

on:
  push:
    branches: [master]
    tags: ["v*"]
  workflow_dispatch:

jobs:
  flakehub-publish:
    name: Publish to FlakeHub
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Publish to FlakeHub
        uses: DeterminateSystems/flakehub-push@main
        with:
          name: gui-wf/resend-mcp-server
          rolling: true
          visibility: public
